// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmllzmixcbqzvarqpsjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbGx6bWl4Y2JxenZhcnFwc2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MDE1NTYsImV4cCI6MjA5MDM3NzU1Nn0.aMueEXJ4yxAXwPjL-r-wt9Nw7v4oxNhiXNpNy8as-O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});